### ISSUE TITLE
renderers

### ISSUE THREAD

**Issue by sabinadreves** [eclipsesource/jsonforms-vue-seed#6]
Hello, i just wanted to ask if it is possible to use the material renderers also for vuejs or is it just for react ? 

kind regards :)

**Comment by sdirix** [comment]
Hi @swana1337, please ask questions on the [discussion board](https://spectrum.chat/jsonforms?tab=posts) instead of creating issues.

We have two published material renderer sets, one based on Material UI for React and one based on Angular Material for Angular. At the moment we don't publish a material renderer set for Vue.

**Comment by sabinadreves** [comment]
I will, sorry. 

Will there be also one for vue in the next updates ?

**Comment by sdirix** [comment]
Hi @swana1337, we don't currently plan to create or maintain a separate Material renderer set for Vue. However if you're interested in that you might want to look into our [professional support](https://jsonforms.io/support) options. We could help you in creating and maintaining such a renderer set from design tips to taking over the full implementation.
